image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  tags:
    - tsn
  script:
    - hugo --gc --minify --enableGitInfo
  artifacts:
    paths:
    - public
  only:
  - main
